apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mono-dmongodb
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb 
  template:
    metadata:
      labels: 
         app: mongodb 
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6
          args: ["--dbpath","/data/db"]
          command: 
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"
          ports:
           - containerPort: 27017
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits: 
              memory: "1000Mi"
              cpu: "500m"
          env:
           - name: MONGO_INITDB_ROOT_USERNAME
             valueFrom:
               secretKeyRef:
                 name: mongo-db-secret
                 key: username
           - name: MONGO_INITDB_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mongo-db-secret
                 key: password
          volumeMounts:
            - name: manogo-db-volume
              mountPath: /data/db
      volumes:
        - name: manogo-db-volume
          persistentVolumeClaim: 
            claimName: manogo-db-volume-claim
