apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manogo-db-volume-claim
  namespace: app
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
